#!/usr/bin/env zsh

if [ -f /var/lib/snapd/desktop/applications/netron_netron.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/netron.svg|g' /var/lib/snapd/desktop/applications/netron_netron.desktop
fi
