#!/usr/bin/env zsh

if [ -f /var/lib/snapd/desktop/applications/octave_octave.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/octave.svg|g' /var/lib/snapd/desktop/applications/octave_octave.desktop
fi
