#!/usr/bin/env zsh

if [ -f /var/lib/snapd/desktop/applications/vlc_vlc.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/vlc.svg|g' /var/lib/snapd/desktop/applications/vlc_vlc.desktop
fi
