#!/usr/bin/env zsh

[ ! -d /usr/share/icons/Numix-Square ] && exit

if [ -f /var/lib/snapd/desktop/applications/netron_netron.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/netron.svg|g' /var/lib/snapd/desktop/applications/netron_netron.desktop
fi
