#!/usr/bin/env zsh

local _ax_this_dir="${0:a:h}"

update_all() {
    local _ax_application_name

    cd "${_ax_this_dir}"
    foreach script in update*icon
    do
        _ax_application_name=$(echo "${script}" | sed -e 's/.*update-//' | sed -e 's/icon//')
        printf "Updating %s icon...\n" "${_ax_application_name}"
        "${_ax_this_dir}/${script}"
    done
}

update_all
