#!/usr/bin/env zsh

if [ -f /var/lib/snapd/desktop/applications/brave_brave.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/brave.svg|g' /var/lib/snapd/desktop/applications/brave_brave.desktop
fi
