#!/usr/bin/env zsh

if [ -f /var/lib/snapd/desktop/applications/htop_htop.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/htop.svg|g' /var/lib/snapd/desktop/applications/htop_htop.desktop
fi
