#!/usr/bin/env zsh

if [ -f /var/lib/snapd/desktop/applications/firefox_firefox.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/firefox.svg|g' /var/lib/snapd/desktop/applications/firefox_firefox.desktop
fi
