#!/usr/bin/env bash

if [ -f /var/lib/snapd/desktop/applications/remmina_remmina.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/remmina.svg|g' /var/lib/snapd/desktop/applications/remmina_remmina.desktop
fi
