#!/usr/bin/env zsh

if [ -f /var/lib/snapd/desktop/applications/code_code.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/vscode.svg|g' /var/lib/snapd/desktop/applications/code_code.desktop
fi
