#!/usr/bin/env zsh

[ ! -d /usr/share/icons/Numix-Square ] && exit

if [ -f /var/lib/snapd/desktop/applications/obsidian_obsidian.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/obsidian.svg|g' /var/lib/snapd/desktop/applications/obsidian_obsidian.desktop
fi

