- name: Install vim-plug for Neovim
  hosts: localhost
  become: false
  tasks:
    - name: Ensure Neovim autoload directory exists
      file:
        path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
        state: directory
        mode: '0755'

    - name: Download vim-plug for Neovim
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
        mode: '0644'

    - name: Install plugins using vim-plug
      command: nvim +PlugInstall --sync +qa!
      args:
        creates: "{{ ansible_env.HOME }}/.local/share/nvim/plugged"
