- name: Set ZSH as the default shell
  hosts: all
  tasks:
    - name: Ensure ZSH is installed
      apt:
        name: zsh
        state: present

    - name: Change default shell to ZSH
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh
