# asdf plugins to install (from your install script)
asdf_plugins:
  - bat
  - choose
  - dive
#  - dotnet
#  - elixir
#  - erlang
  - eza
  - fd
  - fzf
  - github-cli
#  - java
  - jq
#  - julia
  - neovim
#  - nodejs
  - ripgrep
#  - shellcheck
  - tokei
  - uv
  - yq
