---
- name: Detect Ubuntu version
  ansible.builtin.command: lsb_release -rs
  register: ubuntu_version
  changed_when: false

- name: Install Papirus icons (Ubuntu 24.04)
  when: ubuntu_version.stdout == "24.04"
  block:
    - name: Add Papirus PPA
      ansible.builtin.apt_repository:
        repo: ppa:papirus/papirus
        state: present
      become: true

    - name: Install Papirus icon theme
      ansible.builtin.apt:
        name: papirus-icon-theme
        state: present
        update_cache: true
      become: true
