---
- name: Install Papirus icons
  block:
    - name: Add Papirus PPA
      ansible.builtin.apt_repository:
        repo: ppa:papirus/papirus
        state: present
      become: true

    - name: Install Papirus icon theme
      ansible.builtin.apt:
        name: papirus-icon-theme
        state: present
        update_cache: true
      become: true
