#! /usr/bin/env zsh

# clear-fscache: Clear filesystem caches

[[ "$1" == "--help" ]] && echo "Usage: ${0:t}" && return 0

# Sync and drop caches
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
