#! /usr/bin/env zsh


# Variables --------------------------------------------------------------------
local _synopsis="Synopsis:
    ${0:t} <PLUGIN>

See also:
    ${0:t} --help
"
local _help="Description:
    Compare <PLUGIN> local version with remote version.

Usage:
    ${0:t} <PLUGIN>

Options:
    --help      Show this help message.

Examples:
    ${0:t} bat
    foreach app in choose fd yq; do ${0:t} \$app; done
"


# Functions --------------------------------------------------------------------
_synopsis() {
    echo "${_synopsis}" | tail --lines=+2
}

_help() {
    echo "${_help}" | tail --lines=+2
}


# Options ----------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)     _help_flag=true ;;
        *)          _arg=$1         ;;
    esac
    shift
done


# Main -------------------------------------------------------------------------
[[ -n $_help_flag ]] && _help && exit 0


# Driver -----------------------------------------------------------------------
function compare_asdfpluginversion() {
    if command -v asdf > /dev/null 2>&1
    then
        local __AX_YELLOW=$(tput setaf 3)
        local __AX_NORMAL=$(tput sgr0)
        local __AX_COLUMNS="%-15s %-15s %s\n"
        local __AX_PLUGIN=""

        printf "${__AX_COLUMNS}" "Plugin" "Current" "Latest"
        foreach __AX_PLUGIN in $(asdf plugin list)
        do
            [[ "${__AX_PLUGIN}" == "java" ]] && continue
            local __AX_CURRENT=$(asdf current "${__AX_PLUGIN}" | tr -s " " | cut -d" " -f2)
            local __AX_LATEST=$(asdf latest "${__AX_PLUGIN}")
            [[ "${__AX_CURRENT}" != "${__AX_LATEST}" ]] && __AX_LATEST="${__AX_YELLOW}${__AX_LATEST}${__AX_NORMAL}"
            printf "${__AX_COLUMNS}" "${__AX_PLUGIN}" "${__AX_CURRENT}" "${__AX_LATEST}"
        done
        printf "\n"
    else
        printf "%s\n" "asdf is not installed"
    fi
}


compare_asdfpluginversion


unfunction _synopsis
unfunction _help
unfunction compare_asdfpluginversion
