#! /usr/bin/env zsh

# get-githubgitignores: List all available GitHub gitignore templates

[[ "$1" == "--help" ]] && echo "Usage: get-githubgitignores" && return 0

# Fetch and display gitignore templates
curl -s -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/gitignore/templates \
    | jq -r '.[]' \
    | awk 'BEGIN{print "Language"; print "---------------------------"} {print}' \
    | less -R
