#! /usr/bin/env zsh

# get-latestasdf: Display latest asdf version and release date

[[ "$1" == "--help" ]] && echo "Usage: get-latestasdf" && return 0

# Fetch and display latest release info
local version_info=$(wget -qO- 'https://api.github.com/repos/asdf-vm/asdf/releases/latest' | jq '.|{"version": .tag_name, "at": .created_at}')
echo "version:" $(echo "${version_info}" | jq '.version' | sed -e 's/"//g')
echo "date:   " $(echo "${version_info}" | jq '.at'      | sed -e 's/"//g')
