#! /usr/bin/env zsh

# get-latestasdf: Display latest asdf version and release date

[[ "$1" == "--help" ]] && echo "Usage: get-latestasdf" && return 0

# Fetch and display latest release info
echo $(wget -qO- 'https://api.github.com/repos/asdf-vm/asdf/releases/latest' \
    | jq -r '. | "\(.tag_name) released on \(.created_at[:10])"')
