#! /usr/bin/env zsh

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <file>"
  exit 1
fi

local _file="$1"

ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 ${_file} 2>/dev/null

