#! /usr/bin/env zsh

# get-systeminformation: Display system information using fastfetch

[[ "$1" == "--help" ]] && echo "Usage: ${0:t}" && return 0

# Check if fastfetch is installed
if ! command -v fastfetch &> /dev/null; then
    echo "fastfetch could not be found"
    return 1
fi

# Display system information
fastfetch
