#! /usr/bin/env zsh

# Get the Language from the command line. The default is Python.
LANGUAGE=${1:-Python}

curl -s -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/gitignore/templates/${LANGUAGE} | jq -r '.source'

