#! /usr/bin/env zsh

# test-reboot: Check if system reboot is required

[[ "$1" == "--help" ]] && echo "Usage: test-reboot" && return 0

# Check reboot status
[[ -f /var/run/reboot-required ]] && echo "Reboot required!" || echo "No reboot required."
