#! /usr/bin/env zsh

# update-neovimplugs: Update Neovim plugins using vim-plug

[[ "$1" == "--help" ]] && echo "Usage: ${0:t}" && return 0

# Install/update plugins and quit
nvim +'PlugInstall --sync' +'qa'
