# ENVIRONMENT VARIABLES AND EXPORTS
if [[ -x $(which python3) ]] {
    SITE_PACKAGE_HOME=$(python3 -m site --user-site)
    export SITE_PACKAGE_HOME
}


# PATH
typeset -aU path # prevent duplicates
path=(${HOME}/.local/bin $path)
path+=("${HOME}/".zshfunctions)


# FPATH
typeset -aU fpath # prevent duplicates
fpath=(${ASDF_DIR}/completions $fpath)


# MANPATH
