---
- name: Check if dotfiles directory exists
  ansible.builtin.stat:
    path: "{{ duplic8r.home }}/dotfiles"
  register: dotfiles_check

- name: Install dotfiles using Stow
  when: dotfiles_check.stat.exists
  ansible.builtin.command:
    cmd: "stow --target={{ ansible_env.HOME }} {{ item }}"
    chdir: "{{ duplic8r.home }}/dotfiles"
  loop:
    - bat
    - dev
    - git
    - monitor
    - nvim
    - system
    - terminal
    - tmux
    - zsh
  register: stow_result
  changed_when: stow_result.rc == 0
  failed_when: stow_result.rc != 0

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Create .local/bin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'
