- name: Install ctrl+r (history-search-multi-word)
  hosts: localhost
  become: false
  gather_facts: true
  tasks:
    - name: Ensure history-search-multi-word is installed or updated
      git:
        repo: "https://github.com/zdharma-continuum/history-search-multi-word.git"
        dest: "{{ ansible_env.HOME }}/.zsh-hsmw"
        version: "c4dcddc1cd17e7e0909471703f3526170db0f475"
        update: true
