- name: Install snaps packages
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    snaps:
      - brave
      - chromium
      - "code --classic"
      - "obsidian --classic"
      - slack
      - slides
  tasks:
    - name: Refresh snaps
      command: snap refresh

    - name: Install snap packages
      command: snap install {{ item }}
      loop: "{{ snaps }}"
