#!/usr/bin/env zsh

[ ! -d /usr/share/icons/Numix-Square ] && exit

if [ -f /var/lib/snapd/desktop/applications/chromium_chromium.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/chromium.svg|g' /var/lib/snapd/desktop/applications/chromium_chromium.desktop
fi
