#!/usr/bin/env zsh

[ ! -d /usr/share/icons/Numix-Square ] && exit

if [ -f /var/lib/snapd/desktop/applications/htop_htop.desktop ]; then
    sed -i 's|Icon=.*|Icon=/usr/share/icons/Numix-Square/48/apps/htop.svg|g' /var/lib/snapd/desktop/applications/htop_htop.desktop
fi
