# git-cliff ~ default configuration file
# https://git-cliff.org/docs/configuration
#
# Lines starting with "#" are comments.
# Configuration options are organised into tables and keys.
# See documentation for more information on available options.

[changelog]
# changelog header
header = """
# Changelog\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }}
    **{{ timestamp | date(format="%Y-%m-%d") }}**
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
# remove the leading and trailing white-space from the template
trim = true
# changelog footer
footer = """
"""
# post processors
postprocessors = [
  # { pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" }, # replace repository URL
]
[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for pre processing the commit messages
commit_preprocessors = [
  # { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"}, # replace issue numbers
]
# regex for parsing and grouping commits
commit_parsers = [
  # increment major version
  { message = "^feat!", group = "BREAKING CHANGES" },
  # increment minor version
  { message = "^feat", group = "New & Updated Features" },
  # increment patch version
  { message = "^revert", group = "Reverted Changes" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^hotfix", group = "Critical Bug Fixes" },
  # no increment
  { message = "^build", group = "Updates to the Build System" },
  { message = "^chore", skip = true },
  { message = "^cicd", group = "Updates to the Build, Test and Deployment Pipeline" },
  { message = "^doc", group = "New & Updated Documentation" },
  { message = "^merge", skip = true },
  { message = "^perf", group = "Performance Enhancements" },
  { message = "^refactor", group = "Refactor" },
  { message = "^style", group = "Stylistic & Idiomatic Updates" },
  { message = "^test", group = "Tests" },
  { message = "^wip", skip = true },
  { body = ".*security", group = "Security Enhancements" },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# regex for matching git tags
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+(-(alpha|beta)\\.[1-9]+[0-9]*$)?"
# regex for skipping tags
skip_tags = ""
# regex for ignoring tags
ignore_tags = ""
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# limit the number of commits included in the changelog.
# limit_commits = 42
